### ISSUE TITLE
Please seperate guide for 3.5 and 4.1

### ISSUE THREAD

**Issue by haodketernal** [TheHive-Project/docs#5]
Please seperate guide for 3.5 and 4.1. 
Sometime I confused when reading the guide. I'm not sure it's can run on 3.4-3.5 version or not

**Comment by jeromeleonard** [comment]
Our current version is 4.x. The main and updated documentation is then focused on TheHive 4. You can find the specific documentation for previous version in the "Legacy" part. 
![2021-08-31_09-13-12](https://user-images.githubusercontent.com/10532879/131459259-069402f1-d65d-4905-9d53-c7ba2bd842c0.png)
