### ISSUE TITLE
[API] Add user API docs

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/docs#7]
Add documentation of the following APIs:

- [x] Create user
- [x] Update user
- [x] List/search users
- [x] Set user password
- [x] Generate API key for a user
- [x] Revoke API key of a user
- [x] Get API key of a user
- [x] Lock user
- [x] Delete user
- [x] Review

**Comment by To-om** [comment]
The documentation doesn't contains information on how the user avatar is retrieved nor updated.
